# Generated by Django 5.0.6 on 2024-06-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_author_publisher_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
