# Generated by Django 5.0.6 on 2024-06-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_author_publisher_book_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='member',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
