# Generated by Django 5.0.6 on 2024-06-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_club_trainers_players_payments_trainingkitcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='Trainers',
            new_name='Trainer',
        ),
    ]
